config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'home/about' => 'homes#index'
  get 'search' => 'searches#search'
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :messages, only: [:show, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  
  has_many :view_counts, dependent: :destroy
  
  

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(search, word)
    if search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
     @book = Book.all
    end
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :content, presence: true, length: { maximum: 140 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
  has_many :entries
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # foreign_key（FK）には、@user.xxxとした際に「@user.idがfollower_idなのかfollowed_idなのか」を指定します。
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # @user.booksのように、@user.yyyで、
  # そのユーザがフォローしている人orフォローされている人の一覧を出したい
  has_many :followings, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :messages
  has_many :entries
  has_many :rooms, through: :entries

  has_many :view_counts, dependent: :destroy

  def follow(user_id)
    active_relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    active_relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.search(search,word)
    if search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "perfect_match"
      @user = User.where("name LIKE?","#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  attachment :profile_image
  validates :name, presence: true
  validates :name,length: { minimum: 2, maximum: 20 }
  validates :name, uniqueness: true
  validates :introduction, length: { maximum: 50 }

end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id)
      flash[:success] = "successfully"
    else
      @books = Book.all
      @user = @book.user
      render :index
      flash[:error] = "error"
    end
  end

  def index
    @book = Book.new
    @books = Book.find(Favorite.group(:book_id).where(created_at: Time.current.all_week).order('count(book_id) desc').pluck(:book_id))
  end

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
    @book_comments = @book.book_comments

    unless ViewCount.find_by(user_id: current_user.id, book_id: @book.id)
      current_user.view_counts.create(book_id: @book.id)
    end
  end

  def edit
   @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id)
      flash[:success] = "successfully"
    else
      render :edit
      flash[:error] = "error"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
    flash[:success] = "successfully"
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!, except: [:top, :index]
  def top
  end
  
  def index
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:update ]
  before_action :forbid_login_user, only: [:edit]
  before_action :set_book

  def forbid_login_user
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end

  def correct_user
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to root_path
    end
  end

  def index
    @users = User.all.page(params[:page]).reverse_order
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = Book.where(user_id: @user.id)
    
    this_day = Date.today
    @tdbooks = Book.where(user_id: @user.id, created_at: Date.today.beginning_of_day..Date.today.end_of_day).count
    @ysbooks = Book.where(user_id: @user.id, created_at: Date.yesterday.beginning_of_day..Date.yesterday.end_of_day).count
    @this_books = Book.where(user_id: @user.id, created_at: (this_day - (this_day.wday - 6) - 7).beginning_of_day..(this_day - (this_day.wday - 5)).end_of_day).count
    @last_books = Book.where(user_id: @user.id, created_at: ((((this_day - (this_day.wday - 6) - 7)-7).beginning_of_day)..(((this_day - (this_day.wday - 5))- 7 ).end_of_day))).count
    
    begin
      @day_before_ratio = (@tdbooks / @ysbooks) * 100
    rescue
      @day_before_ratio = "0"
    end
    
    begin
      @week_before_ratio = (@this_books / @last_books) * 100
    rescue 
      @week_before_ratio = "0"
    end
    
    
    
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(current_user)
      flash[:success] = "successfully"
    else
      render :edit
      flash[:error] = "error"
    end
  end



  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def set_book
    @newbook = Book.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_commentlist.html.erb
  <table>
   <% book_comments.each do |book_comment| %>
    <tr>
      <td>
        <%= link_to user_path(book_comment.user.id) do %>
          <%= attachment_image_tag book_comment.user, :profile_image, :fill, 40, 40, fallback: "noimage.jpeg" %>
        <% end %>
        <br><%= link_to book_comment.user.name, user_path(book_comment.user.id) %>
      </td>
      <td>
        <%= book_comment.comment %></td>
      <td>
        <% if book_comment.user == current_user %>
          <div class="comment-delete">
            <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-sm btn-danger", remote: true %>
          </div>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/books/_form.html.erb
<%= form_with model: book, local:true do |f| %>
  <div class="form-group">
    <%= f.label :title, 'Title' %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :body, 'Opinion' %>
    <%= f.text_field :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<div class='row'>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% books.each do |book| %>
        <tr id="book_<%= book.id %>">
          <td>
            <%= link_to user_path(book.user) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "noimage.jpeg" %>
            <% end %>
          </td>
          <td><%= link_to book.title, book_path(book.id) %></td>
          <td><%= book.body %></td>
          <td class="favorite-btn"><%= render "favorites/favorite-btn", book: book %></td>
          <td class="comments-count">コメント数: <%= book.book_comments.count %></td>
          <td class="view-count">閲覧数: <%= book.view_counts.count %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<div class="notice">
  <%= render 'layouts/error', book: @book %>
</div>
  <!-- form_with部分 -->
  <%= form_with model:@book, , remote :true do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Opinion</h4>
    <%= f.text_field :body %>
    <h4></h4>
    <h4></h4>
    <div class="form-group">
      <input type="submit" name="commit" value="Update Book" class="btn btn-success" data-disable-with="Update Book" />
    </div>
  <% end %>
  <%= link_to "Show", book_path(@book.id) %>
  <%= link_to "Back", books_path %>

app/views/books/index.html.erb
<div class="notice">
  <%= render 'layouts/error', book: @book %>
</div>
<div class='row'>
  <div class="col-md-3">
    <h1>User info</h1>
      <%= render 'users/info', user: current_user %>
    <h1>New book</h1>
    <%= render 'books/form', book: @book %>
  </div>
  <div class="col-md-8 offset-md-1">
    <h1>Books</h1>
      <%= render 'index', books: @books %>
  </div>
</div>

app/views/books/show.html.erb
<%= flash[:success] %>
<% if @book_comment.errors.any? %>
  <%= @book_comment.errors.count %>件のエラーが発生しました
  <% @book_comment.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<div class='row'>
  <div class="col-md-3">
    <h1>User info</h1>
      <%= render 'users/info', user: @user%>
    <h1>New book</h1>
      <%= render 'books/form', user: @user, book: @book %>
  </div>
  <div class="col-md-8 offset-md-1">
    <h1>Book detail</h1>
    <table class="table">
      <tbody>
        <tr id="book_<%= @book.id %>">
          <td>
            <%= link_to user_path(@user.id) do %>
              <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, fallback: "noimage.jpeg" %>
            <% end %>
            <br><%= link_to @user.name, user_path(@user.id) %>
          </td>
          <td><%= link_to @book.title, book_path(@book.id) %></td>
          <td><%= @book.body %></td>
          <% if current_user.id == @book.user_id %>
            <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to "Destroy", book_path(@book.id), method: :delete, class: "btn btn-sm btn-danger" %></td>
          <% end %>
          <td class="favorite-btn"><%= render "favorites/favorite-btn", book: @book %></td>
          <td class="view-count">閲覧数: <%= @book.view_counts.count %></td>
        </tr>
      </tbody>
    </table>
    <div id="comment-<%= @book.id %>">
      <%= render 'commentlist', user: @user, book_comments: @book_comments %>
    </div>
    <div class="new-comment">
      <%= form_with model: [@book, @book_comment] , remote: true do |f| %>
        <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
        <%= f.submit "送信" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_chat-button.html.erb
<% unless user.id == current_user.id %>
  <% if (current_user.followed_by? user) && (user.followed_by? current_user)  %>
    <% if isRoom == true %>
      <p class="user-show-room"><%= link_to "チャットへ", room_path(roomId), class="btn btn-primary btn-lg" %></a>
    <% else %>
      <%= form_with model: room do |f| %>
        <%= fields_for entry do |e| %>
          <%= e.hidden_field :user_id, value: user.id %>
        <% end %>
        <%= f.submit "チャットを始める", class:"btn btn-primary btn-lg user-show-chat"%>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/users/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td>
          <%= link_to user_path(user) do %>
            <%= attachment_image_tag user, :profile_image, :fill, 40, 40 ,fallback: "noimage.jpeg"%>
          <% end %>
        </td>
        <td>
          <%= link_to user.name, user_path(user) %>
        </td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td>
          <% if user != current_user %>
            <% if current_user.following?(user) %>
              <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to "Show", user_path(user.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate users %>

app/views/users/_info.html.erb
<div class="profile-container">
  <%= attachment_image_tag user, :profile_image, :fill, 100, 100 ,fallback: "noimage.jpeg" %>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><div class="profile-name"><%= user.name %></div></th>
      <tr>
        <th>introduction</th>
        <th><div class="profile-introduction"><%= user.introduction %></div></th>
      </tr>
      <tr>
        <th>
          follows
          <%= link_to user_followings_path(user.id) do %>
            <%= user.followings.count %>
          <% end %>
        </th>
      </tr>
      <tr>
        <th>
          followers
          <%= link_to user_followers_path(user.id) do %>
            <%= user.followers.count %>
          <% end %>
        </th>
      </tr>
      <tr>
        <th>
          <% if user != current_user %>
            <% if current_user.following?(user) %>
              <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
            <% end %>
          <% end %>
        </th>
        <th>
          <% if current_user != user && current_user.following?(user) && user.following?(current_user) %>
            <%= link_to "chatを始める", message_path(user.id) %>
          <% end %>
        </th>
      </tr>
    </tbody>
  </table>
  <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block", method: :get do %>
    <i class="fas fa-user-cog edit_user_255"></i>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="notice">
  <% if @user.errors.any? %>
    <%= @user.errors.count %>件のerrorが発生しました
    <% @user.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>
</div>
<h2>User info</h2>
<%= form_with model:@user, local:true do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  <label for="inputImage">ProfileImage</label>
  <%= f.attachment_field :profile_image, placeholder: "ファイルを選択" %>  
  <label for="inputIntroduction">Introduction</label>
  <%= f.text_area :introduction %>
  <%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<div class='row'>
  <div class="col-md-3">
    <h1>User info</h1>
      <%= render 'info', user: current_user%>
    <h1>New book</h1>
      <%= render 'books/form', user: current_user, book: @book %>
  </div>
  <div class="col-md-8 offset-md-1">
  <h1>Users</h1>
    <%= render 'index', users: @users %>
</div>

app/views/users/show.html.erb
<%= flash[:success] %>
<div class='row'>
  <div class="col-md-3">
    <h1>User info</h1>
      <%= render 'info', user: @user %>
    <h1>New book</h1>
      <%= render 'books/form', book: @book %>
  </div>
  <div class="col-md-8 offset-md-1">
    <h3>Books</h3>
    <%= render 'books/index', books: @books %>

    <!--投稿数表示-->
    <div class="books_counts">
      <table class="table">
        <thead>
          <tr>
            <th>今日の投稿数</th>
            <th>前日の投稿数</th>
            <th>前日比</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @tdbooks %></td>
            <td><%= @ysbooks %></td>
            <td><%= @day_before_ratio %>%</td>
          </tr>
        </tbody>
        <thead>
          
          <tr>
            <th>今週の投稿数</th>
            <th>前週の投稿数</th>
            <th>前週比</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @this_books %></td>
            <td><%= @last_books %></td>
            <td><%= @week_before_ratio %>%</td>
          </tr>
        </tbody>
      </table>
    </div>
    <!--７日間分の投稿数-->
    <div class="">
     <table class="table">
       <thead>
         
       </thead>
       <tbody>
         
       </tbody>
     </table>
    </div>
  </div>
</div>